'use client';
/**
 * QR Scanner Check-In Page
 *
 * Uses the device camera + jsQR to read QR codes generated by /api/qr/generate.
 * Reception staff, trainers, and kiosk devices use this to check in members.
 *
 * Flow: Camera → jsQR frame scan → POST /api/qr/scan → show result → auto-retry
 */
import { useEffect, useRef, useState, useCallback } from 'react';
import { m, AnimatePresence } from 'framer-motion';
import {
  QrCode, CheckCircle2, XCircle, Loader2, RefreshCw,
  Camera, AlertTriangle, Clock, Zap, User, ScanLine,
} from 'lucide-react';
import dynamic from 'next/dynamic';
import Guard from '@/components/Guard';
import AppShell from '@/components/AppShell';
import { api } from '@/lib/api';

// Lazy-load jsQR so it doesn't bloat the server bundle
let jsQR: ((data: Uint8ClampedArray, width: number, height: number) => { data: string } | null) | null = null;

type ScanState = 'idle' | 'loading' | 'scanning' | 'processing' | 'success' | 'error' | 'duplicate' | 'denied';

type ScanResult = {
  success: boolean;
  duplicate?: boolean;
  message: string;
  user?: { id: string; name: string; status: string; photo_url?: string; member_code?: string; role?: string };
};

const STATE_CFG: Record<ScanState, { color: string; label: string }> = {
  idle:       { color: '#94a3b8', label: 'Initialising…' },
  loading:    { color: '#6366f1', label: 'Starting camera…' },
  scanning:   { color: '#06b6d4', label: 'Scanning QR code…' },
  processing: { color: '#8b5cf6', label: 'Verifying…' },
  success:    { color: '#10b981', label: 'Check-in successful' },
  error:      { color: '#ef4444', label: 'Check-in failed' },
  duplicate:  { color: '#f59e0b', label: 'Already checked in' },
  denied:     { color: '#ef4444', label: 'Access denied' },
};

export default function QrScannerPage() {
  const videoRef     = useRef<HTMLVideoElement>(null);
  const canvasRef    = useRef<HTMLCanvasElement>(null);
  const streamRef    = useRef<MediaStream | null>(null);
  const rafRef       = useRef<number>(0);
  const cooldownRef  = useRef<number>(0);
  const retryTimeout = useRef<ReturnType<typeof setTimeout> | null>(null);

  const [scanState, setScanState]  = useState<ScanState>('idle');
  const [result,    setResult]     = useState<ScanResult | null>(null);
  const [recents,   setRecents]    = useState<(ScanResult & { time: string })[]>([]);
  const [cameraErr, setCameraErr]  = useState<string | null>(null);

  const speak = useCallback((text: string) => {
    if (!('speechSynthesis' in window)) return;
    window.speechSynthesis.cancel();
    const u = new SpeechSynthesisUtterance(text);
    u.rate = 1.1;
    window.speechSynthesis.speak(u);
  }, []);

  const scheduleRetry = useCallback(() => {
    if (retryTimeout.current) clearTimeout(retryTimeout.current);
    retryTimeout.current = setTimeout(() => {
      setResult(null);
      setScanState('scanning');
      cooldownRef.current = 0;
    }, 5000);
  }, []);

  const processPayload = useCallback(async (payload: string) => {
    if (Date.now() < cooldownRef.current) return;
    cooldownRef.current = Date.now() + 6000;
    setScanState('processing');

    try {
      const data = await api.qr.scan({ payload });
      setResult(data);
      setRecents((prev) => [{
        ...data,
        time: new Date().toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' }),
      }, ...prev].slice(0, 20));

      if (data.success && !data.duplicate) {
        setScanState('success');
        speak(`Welcome, ${data.user?.name}`);
      } else if (data.duplicate) {
        setScanState('duplicate');
        speak('Already checked in');
      } else {
        setScanState('error');
        speak(data.message);
      }
    } catch (err: unknown) {
      setScanState('error');
      const msg = err instanceof Error ? err.message : 'Network error';
      setResult({ success: false, message: msg });
      speak('Check-in failed');
    }
    scheduleRetry();
  }, [speak, scheduleRetry]);

  const startScanLoop = useCallback(() => {
    const video  = videoRef.current;
    const canvas = canvasRef.current;
    if (!video || !canvas || !jsQR) return;
    const ctx = canvas.getContext('2d', { willReadFrequently: true });
    if (!ctx) return;

    function tick() {
      if (!video || video.readyState < 2) { rafRef.current = requestAnimationFrame(tick); return; }
      canvas!.width  = video.videoWidth;
      canvas!.height = video.videoHeight;
      ctx!.drawImage(video, 0, 0);
      const imgData = ctx!.getImageData(0, 0, canvas!.width, canvas!.height);
      const code = jsQR!(imgData.data, imgData.width, imgData.height);
      if (code?.data && Date.now() >= cooldownRef.current) {
        void processPayload(code.data);
      }
      rafRef.current = requestAnimationFrame(tick);
    }
    rafRef.current = requestAnimationFrame(tick);
  }, [processPayload]);

  const startCamera = useCallback(async () => {
    setScanState('loading');
    setCameraErr(null);

    if (!jsQR) {
      try {
        const mod = await import('jsqr');
        jsQR = (mod.default || mod) as unknown as typeof jsQR;
      } catch {
        setCameraErr('Could not load QR library. Please refresh.');
        setScanState('idle');
        return;
      }
    }

    try {
      const stream = await navigator.mediaDevices.getUserMedia({
        video: { facingMode: { ideal: 'environment' }, width: { ideal: 1280 }, height: { ideal: 720 } },
      });
      streamRef.current = stream;
      if (videoRef.current) {
        videoRef.current.srcObject = stream;
        videoRef.current.play().catch(() => {});
      }
      setScanState('scanning');
      startScanLoop();
    } catch (err: unknown) {
      const msg = err instanceof Error && err.name === 'NotAllowedError'
        ? 'Camera permission denied. Please allow camera access.'
        : 'Camera not available on this device.';
      setCameraErr(msg);
      setScanState('idle');
    }
  }, [startScanLoop]);

  useEffect(() => {
    import('jsqr').then(mod => { jsQR = (mod.default || mod) as unknown as typeof jsQR; }).catch(() => {});
  }, []);

  useEffect(() => {
    startCamera();
    return () => {
      cancelAnimationFrame(rafRef.current);
      streamRef.current?.getTracks().forEach((t) => t.stop());
      if (retryTimeout.current) clearTimeout(retryTimeout.current);
      window.speechSynthesis?.cancel();
    };
  }, []); // eslint-disable-line

  const sc = STATE_CFG[scanState];
  const isSuccess = scanState === 'success';
  const isError   = scanState === 'error' || scanState === 'denied';
  const isDup     = scanState === 'duplicate';

  return (
    <Guard role="member">
      <AppShell>
        <style>{`
          @keyframes qs-scan { 0% { top: 10%; } 100% { top: 85%; } }
          @keyframes qs-corner { 0%,100% { opacity: 0.6; } 50% { opacity: 1; } }
        `}</style>

        {/* Hero */}
        <div style={{
          background: 'linear-gradient(135deg,#0f172a 0%,#1e1b4b 50%,#0c4a6e 100%)',
          borderRadius: 16, padding: '20px 24px', marginBottom: 20,
          border: '1px solid rgba(6,182,212,0.2)',
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
            <div style={{ width: 44, height: 44, borderRadius: 14, background: 'linear-gradient(135deg,#06b6d4,#0284c7)', display: 'flex', alignItems: 'center', justifyContent: 'center', boxShadow: '0 4px 20px rgba(6,182,212,0.3)' }}>
              <QrCode size={22} color="#fff" />
            </div>
            <div>
              <h1 style={{ fontSize: 20, fontWeight: 800, color: '#fff', margin: 0, letterSpacing: '-0.02em' }}>QR Check-In Scanner</h1>
              <p style={{ fontSize: 12, color: 'rgba(255,255,255,0.5)', margin: '3px 0 0', display: 'flex', alignItems: 'center', gap: 6 }}>
                <span style={{ width: 5, height: 5, borderRadius: '50%', background: scanState === 'scanning' ? '#10b981' : '#94a3b8', display: 'inline-block' }} />
                {sc.label}
              </p>
            </div>
            <div style={{ marginLeft: 'auto', display: 'flex', alignItems: 'center', gap: 6, padding: '4px 12px', borderRadius: 20, background: 'rgba(6,182,212,0.12)', border: '1px solid rgba(6,182,212,0.25)', color: '#06b6d4', fontSize: 11, fontWeight: 700 }}>
              <Clock size={10} />
              {recents.length} today
            </div>
          </div>
        </div>

        <div className="rg-sidebar">

          {/* Camera */}
          <div style={{ background: 'var(--bg-card)', borderRadius: 16, border: '1px solid var(--border)', overflow: 'hidden' }}>
            <div style={{ position: 'relative', width: '100%', aspectRatio: '4/3', background: '#0f172a', overflow: 'hidden' }}>
              <video ref={videoRef} autoPlay playsInline muted style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'cover' }} />
              <canvas ref={canvasRef} style={{ display: 'none' }} />

              {/* QR guide frame */}
              {scanState === 'scanning' && (
                <div style={{ position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%,-50%)', width: 220, height: 220 }}>
                  {/* Corner brackets */}
                  {[['0%','0%','right','bottom'],['100%','0%','left','bottom'],['0%','100%','right','top'],['100%','100%','left','top']].map(([left, top, br, bb], i) => (
                    <div key={i} style={{ position: 'absolute', left, top, width: 30, height: 30, borderRight: br === 'right' ? 'none' : '3px solid #06b6d4', borderLeft: br === 'right' ? '3px solid #06b6d4' : 'none', borderBottom: bb === 'bottom' ? 'none' : '3px solid #06b6d4', borderTop: bb === 'bottom' ? '3px solid #06b6d4' : 'none', animation: 'qs-corner 1.5s ease-in-out infinite', animationDelay: `${i*0.15}s`, transform: left === '0%' && top === '0%' ? 'none' : left === '100%' && top === '0%' ? 'translateX(-100%)' : left === '0%' && top === '100%' ? 'translateY(-100%)' : 'translate(-100%,-100%)' }} />
                  ))}
                  {/* Scan line */}
                  <div style={{ position: 'absolute', left: 0, right: 0, height: 2, background: 'linear-gradient(90deg,transparent,#06b6d4,transparent)', animation: 'qs-scan 2s ease-in-out infinite', boxShadow: '0 0 10px rgba(6,182,212,0.6)' }} />
                </div>
              )}

              {/* Result overlay */}
              <AnimatePresence>
                {result && (
                  <m.div
                    initial={{ opacity: 0, scale: 0.8 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0 }}
                    style={{ position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', background: isSuccess ? 'rgba(16,185,129,0.85)' : isError ? 'rgba(239,68,68,0.85)' : 'rgba(245,158,11,0.85)', backdropFilter: 'blur(4px)' }}
                  >
                    <div style={{ textAlign: 'center', color: '#fff', padding: 24 }}>
                      {isSuccess ? <CheckCircle2 size={56} style={{ margin: '0 auto 12px' }} /> : isError ? <XCircle size={56} style={{ margin: '0 auto 12px' }} /> : <AlertTriangle size={56} style={{ margin: '0 auto 12px' }} />}
                      <div style={{ fontSize: 22, fontWeight: 800, marginBottom: 6 }}>{result.user?.name || (isDup ? 'Already In' : 'Failed')}</div>
                      <div style={{ fontSize: 14, opacity: 0.9 }}>{result.message}</div>
                      {result.user?.member_code && <div style={{ fontSize: 11, opacity: 0.7, marginTop: 4 }}>#{result.user.member_code}</div>}
                    </div>
                  </m.div>
                )}
              </AnimatePresence>

              {/* Camera error */}
              {cameraErr && (
                <div style={{ position: 'absolute', inset: 0, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 12, padding: 24, background: 'rgba(15,23,42,0.95)', textAlign: 'center' }}>
                  <Camera size={36} color="#94a3b8" />
                  <p style={{ color: '#f87171', fontSize: 13, margin: 0 }}>{cameraErr}</p>
                  <button onClick={startCamera} style={{ padding: '8px 20px', borderRadius: 10, border: 'none', background: '#06b6d4', color: '#fff', fontWeight: 700, fontSize: 12, cursor: 'pointer' }}>
                    <RefreshCw size={12} style={{ display: 'inline', marginRight: 6 }} /> Retry
                  </button>
                </div>
              )}

              {/* Status pill */}
              <div style={{ position: 'absolute', bottom: 12, left: '50%', transform: 'translateX(-50%)', display: 'inline-flex', alignItems: 'center', gap: 6, padding: '5px 14px', borderRadius: 100, background: 'rgba(15,23,42,0.8)', backdropFilter: 'blur(8px)', border: '1px solid rgba(255,255,255,0.1)', color: sc.color, fontSize: 11, fontWeight: 700, whiteSpace: 'nowrap' }}>
                <ScanLine size={11} />
                {sc.label}
              </div>
            </div>

            {/* Processing indicator */}
            {scanState === 'processing' && (
              <div style={{ padding: '12px 20px', display: 'flex', alignItems: 'center', gap: 8, background: 'rgba(139,92,246,0.08)', borderTop: '1px solid rgba(139,92,246,0.2)', color: '#8b5cf6', fontSize: 12 }}>
                <Loader2 size={13} style={{ animation: 'spin 0.9s linear infinite' }} />
                Verifying QR code with server…
              </div>
            )}
          </div>

          {/* Right panel */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>

            {/* Instructions */}
            <div style={{ background: 'var(--bg-card)', borderRadius: 14, border: '1px solid var(--border)', padding: 16 }}>
              <div style={{ fontSize: 12, fontWeight: 700, color: 'var(--text-secondary)', marginBottom: 12, display: 'flex', alignItems: 'center', gap: 6 }}>
                <Zap size={12} color="#06b6d4" /> How to use
              </div>
              {[
                'Hold the member\'s QR code in front of the camera',
                'Maintain 15–30 cm distance for best results',
                'Check-in is automatic — no button press needed',
                'Result appears with audio confirmation',
              ].map((tip, i) => (
                <div key={i} style={{ display: 'flex', gap: 8, marginBottom: 8, fontSize: 12, color: 'var(--text-muted)', lineHeight: 1.4 }}>
                  <span style={{ width: 18, height: 18, borderRadius: '50%', background: 'rgba(6,182,212,0.12)', color: '#06b6d4', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 10, fontWeight: 800, flexShrink: 0 }}>{i + 1}</span>
                  {tip}
                </div>
              ))}
            </div>

            {/* Recent check-ins */}
            <div style={{ background: 'var(--bg-card)', borderRadius: 14, border: '1px solid var(--border)', overflow: 'hidden' }}>
              <div style={{ padding: '12px 16px', borderBottom: '1px solid var(--border)', fontSize: 12, fontWeight: 700, color: 'var(--text-secondary)', display: 'flex', justifyContent: 'space-between' }}>
                <span style={{ display: 'flex', alignItems: 'center', gap: 6 }}><Clock size={12} color="#06b6d4" /> Recent</span>
                {recents.length > 0 && <button onClick={() => setRecents([])} style={{ border: 'none', background: 'none', cursor: 'pointer', color: 'var(--text-muted)', fontSize: 11 }}>Clear</button>}
              </div>
              <div style={{ maxHeight: 360, overflowY: 'auto' }}>
                {recents.length === 0 ? (
                  <div style={{ padding: '24px 16px', textAlign: 'center', color: 'var(--text-muted)', fontSize: 12 }}>
                    <QrCode size={20} style={{ margin: '0 auto 8px', display: 'block', opacity: 0.3 }} />
                    No scans yet
                  </div>
                ) : recents.map((r, i) => (
                  <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '9px 14px', borderBottom: '1px solid var(--border)' }}>
                    <div style={{ width: 30, height: 30, borderRadius: '50%', background: r.success ? 'rgba(16,185,129,0.15)' : 'rgba(239,68,68,0.15)', color: r.success ? '#10b981' : '#ef4444', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 10, fontWeight: 800, flexShrink: 0 }}>
                      {r.user?.name?.slice(0, 2).toUpperCase() || '?'}
                    </div>
                    <div style={{ flex: 1, minWidth: 0 }}>
                      <div style={{ fontSize: 12, fontWeight: 600, color: 'var(--text-primary)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{r.user?.name || 'Unknown'}</div>
                      <div style={{ fontSize: 10, color: 'var(--text-muted)' }}>{r.time} · {r.message}</div>
                    </div>
                    {r.success ? <CheckCircle2 size={14} color="#10b981" /> : <XCircle size={14} color="#ef4444" />}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </AppShell>
    </Guard>
  );
}
