'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import {
  Activity, Bot, BrainCircuit, Building2, ChevronRight, CircleDollarSign, Database,
  Gauge, HeartPulse, KeyRound, Layers3, LifeBuoy, LineChart, LockKeyhole, Network,
  PlayCircle, RefreshCw, Route, ServerCog, ShieldCheck, Sparkles, Users2, WandSparkles,
  Workflow, Zap,
} from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { api } from '@/lib/api';
import type { AiModelUsage, AiOverview, AiRouting, AiStudioUsage, AiTrendPoint, CommandCenterSnapshot } from '@/lib/api';

const COLORS: Record<string, string> = {
  healthy: '#10b981', warning: '#f59e0b', timeout: '#f97316', critical: '#ef4444', unavailable: '#94a3b8',
};

const MODULES = [
  ['Studios', Building2, 'studios', '#06b6d4', 'Tenants & lifecycle'],
  ['AI Control', Bot, 'ai', '#8b5cf6', 'Models & routing'],
  ['Analytics', LineChart, 'analytics', '#3b82f6', 'Growth & trends'],
  ['Finance', CircleDollarSign, 'finance', '#10b981', 'Billing & revenue'],
  ['Security', LockKeyhole, 'security', '#f43f5e', 'Threats & access'],
  ['System Health', HeartPulse, 'health', '#f59e0b', 'Infrastructure'],
  ['Storage', Database, 'storage', '#6366f1', 'Files & capacity'],
  ['Support', LifeBuoy, 'support', '#0ea5e9', 'Tickets & service'],
  ['Users', Users2, 'users', '#d946ef', 'Platform accounts'],
  ['Audit', ShieldCheck, 'audit', '#64748b', 'Evidence trail'],
  ['Features', WandSparkles, 'features', '#f97316', 'Feature flags'],
  ['Announcements', Zap, 'announcements', '#eab308', 'Broadcast centre'],
] as const;

const fmt = (n: number) => n >= 1e9 ? `${(n / 1e9).toFixed(2)}B` : n >= 1e6 ? `${(n / 1e6).toFixed(2)}M` : n >= 1e3 ? `${(n / 1e3).toFixed(1)}K` : n.toLocaleString('en-IN');

function Card({ children, glow = 'rgba(99,102,241,.10)' }: { children: React.ReactNode; glow?: string }) {
  return <div className="relative overflow-hidden rounded-[26px] border p-4 sm:p-5" style={{ borderColor: 'var(--border)', background: 'linear-gradient(145deg,color-mix(in srgb,var(--surface) 94%,transparent),color-mix(in srgb,var(--bg-subtle) 92%,transparent))', boxShadow: '0 20px 60px rgba(15,23,42,.07),inset 0 1px 0 rgba(255,255,255,.55)' }}><div aria-hidden className="pointer-events-none absolute -right-16 -top-16 h-36 w-36 rounded-full blur-3xl" style={{ background: glow }} /><div className="relative">{children}</div></div>;
}

function Donut3D({ counts }: { counts: Record<string, number> }) {
  const entries = Object.entries(counts);
  const total = Math.max(1, entries.reduce((a, [, v]) => a + v, 0));
  const r = 39; const circumference = 2 * Math.PI * r; let offset = 0;
  const healthy = counts.healthy ?? 0;
  return <div className="relative h-[174px] w-[174px] shrink-0"><svg viewBox="0 0 100 100" className="h-full w-full -rotate-90 drop-shadow-[0_14px_18px_rgba(15,23,42,.15)]"><circle cx="50" cy="54" r={r} fill="none" stroke="rgba(15,23,42,.12)" strokeWidth="12" opacity=".35" />{entries.map(([name, value]) => { const len = value / total * circumference; const node = <circle key={name} cx="50" cy="50" r={r} fill="none" stroke={COLORS[name] ?? '#94a3b8'} strokeWidth="12" strokeLinecap="round" strokeDasharray={`${Math.max(0, len - 2)} ${circumference}`} strokeDashoffset={-offset} />; offset += len; return node; })}<circle cx="50" cy="50" r="29" fill="var(--surface)" /></svg><div className="absolute inset-0 flex flex-col items-center justify-center"><div className="text-[25px] font-[900]" style={{ color: 'var(--text-primary)' }}>{Math.round(healthy / total * 100)}%</div><div className="text-[9px] font-[800] uppercase tracking-[.14em]" style={{ color: 'var(--text-tertiary)' }}>healthy</div></div></div>;
}

function Routing({ routing }: { routing: AiRouting | null }) {
  const tiers = [
    ['Primary', 'primary', '#8b5cf6', BrainCircuit, 'Client-facing intelligence'],
    ['Secondary', 'secondary', '#06b6d4', Route, 'Operational workloads'],
    ['Fallback', 'fallback', '#f59e0b', ServerCog, 'Safety net'],
  ] as const;
  return <div className="grid gap-2 lg:grid-cols-[1fr_auto_1fr_auto_1fr] lg:items-center">{tiers.flatMap(([label, key, color, Icon, copy], i) => { const node = <div key={key} className="rounded-[20px] border p-3.5" style={{ borderColor: `${color}35`, background: `linear-gradient(145deg,${color}12,transparent)` }}><div className="flex items-center justify-between gap-2"><span className="flex items-center gap-2 text-[11px] font-[850]" style={{ color }}><Icon size={14} />{label}</span><span className="rounded-full px-2 py-0.5 text-[8px] font-[800] uppercase" style={{ background: `${color}16`, color }}>Live config</span></div><div className="mt-2 truncate font-mono text-[11px] font-[700]" style={{ color: 'var(--text-primary)' }}>{routing?.effective?.[key] ?? 'Not configured'}</div><div className="mt-1 text-[10px]" style={{ color: 'var(--text-tertiary)' }}>{copy}</div></div>; return i < 2 ? [node, <div key={`${key}-arrow`} className="hidden justify-center lg:flex"><ChevronRight size={18} style={{ color: 'var(--text-disabled)' }} /></div>] : [node]; })}</div>;
}

export default function PremiumCommandCenterOverviewFixed() {
  const router = useRouter();
  const [state, setState] = useState<{ snapshot: CommandCenterSnapshot | null; ai: AiOverview | null; models: AiModelUsage[]; studios: AiStudioUsage[]; trend: AiTrendPoint[]; routing: AiRouting | null }>({ snapshot: null, ai: null, models: [], studios: [], trend: [], routing: null });
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async (fresh = false) => { setBusy(true); setError(''); try { const [snapshot, ai, models, studios, trend, routing] = await Promise.all([api.superAdmin.commandCenter({ fresh }), api.superAdmin.aiOverview(30), api.superAdmin.aiByModel(30), api.superAdmin.aiByStudio(30), api.superAdmin.aiTrend(30), api.superAdmin.aiRouting()]); setState({ snapshot: snapshot.data, ai: ai.data, models: models.data, studios: studios.data, trend: trend.data, routing: routing.data }); } catch (e: unknown) { setError(e instanceof Error ? e.message : 'Could not load Command Center data.'); } finally { setLoading(false); setBusy(false); } }, []);
  useEffect(() => { void load(); }, [load]);

  const counts = useMemo(() => { const cards = state.snapshot ? Object.values(state.snapshot.cards) : []; return cards.reduce<Record<string, number>>((a, c) => { a[c.status] = (a[c.status] ?? 0) + 1; return a; }, {}); }, [state.snapshot]);
  const trend = useMemo(() => state.trend.map((p) => ({ day: p.day.slice(5), tokens: p.tokens })), [state.trend]);
  const modelBars = useMemo(() => state.models.slice(0, 8).map((m) => ({ model: (m.model || 'unknown').split('/').pop()?.slice(0, 18) ?? 'unknown', requests: m.requests })), [state.models]);
  const studioBars = useMemo(() => state.studios.slice(0, 7).map((s) => ({ studio: (s.organization_name || 'Unknown').slice(0, 16), tokens: s.tokens })), [state.studios]);
  const total = Object.values(counts).reduce((a, b) => a + b, 0); const healthy = counts.healthy ?? 0;
  const attention = (counts.critical ?? 0) + (counts.timeout ?? 0) + (counts.warning ?? 0);
  const status = state.snapshot?.status ?? 'unavailable'; const aiRequests = state.ai?.requests ?? 0; const aiTokens = state.ai?.tokens ?? 0; const fallback = state.ai?.fallback_pct ?? 0;

  if (loading) return <div className="flex min-h-[520px] items-center justify-center"><RefreshCw size={24} className="animate-spin" style={{ color: 'var(--brand)' }} /></div>;
  if (error && !state.snapshot) return <div className="rounded-[24px] border p-8 text-center" style={{ borderColor: 'var(--border)', background: 'var(--surface)' }}><p className="text-sm" style={{ color: 'var(--text-secondary)' }}>{error}</p><button onClick={() => void load(true)} className="mt-3 rounded-xl px-4 py-2 text-xs font-bold text-white" style={{ background: 'var(--brand)' }}>Retry</button></div>;

  const kpis = [
    ['Platform health', status, `${healthy}/${total || 0} healthy signals`, HeartPulse, COLORS[status] ?? '#64748b'],
    ['AI requests', aiRequests.toLocaleString('en-IN'), 'last 30 days', Bot, '#8b5cf6'],
    ['AI tokens', fmt(aiTokens), `${fallback}% fallback rate`, Zap, '#06b6d4'],
    ['Attention', String(attention), 'signals needing review', ShieldCheck, attention ? '#f59e0b' : '#10b981'],
    ['Collection', `${state.snapshot?.duration_ms ?? 0}ms`, 'live snapshot duration', Activity, '#10b981'],
  ] as const;

  return <div className="relative space-y-5 overflow-hidden pb-8"><div aria-hidden className="pointer-events-none absolute -left-40 -top-40 h-[420px] w-[420px] rounded-full blur-3xl" style={{ background: 'rgba(139,92,246,.10)' }} /><div aria-hidden className="pointer-events-none absolute -right-48 top-[260px] h-[520px] w-[520px] rounded-full blur-3xl" style={{ background: 'rgba(6,182,212,.08)' }} />
    <div className="relative flex flex-wrap items-end justify-between gap-4"><div><div className="flex items-center gap-2 text-[10px] font-[850] uppercase tracking-[.18em]" style={{ color: 'var(--brand)' }}><Sparkles size={12} /> Super Admin Command Center 2.0</div><h1 className="mt-1 text-[30px] font-[950] tracking-[-.045em] sm:text-[40px]" style={{ color: 'var(--text-primary)' }}>Platform, at a glance.</h1><p className="mt-1 max-w-[760px] text-[12.5px] leading-relaxed" style={{ color: 'var(--text-secondary)' }}>A premium control plane inspired by FreeLLMAPI routing, fallback chains, analytics and observability — adapted to MY PT STUDIO.</p></div><button onClick={() => void load(true)} disabled={busy} className="flex items-center gap-2 rounded-[13px] border px-3.5 py-2.5 text-[11px] font-[800] disabled:opacity-60" style={{ borderColor: 'var(--border)', background: 'var(--surface)', color: 'var(--text-primary)' }}><RefreshCw size={13} className={busy ? 'animate-spin' : ''} /> Refresh live data</button></div>

    <div className="grid grid-cols-2 gap-3 xl:grid-cols-5">{kpis.map(([label, value, sub, Icon, color]) => <Card key={label} glow={`${color}18`}><div className="flex items-start justify-between"><span className="rounded-xl p-2" style={{ background: `${color}12`, color }}><Icon size={16} /></span><span className="h-2 w-2 rounded-full" style={{ background: color, boxShadow: `0 0 14px ${color}` }} /></div><div className="mt-4 text-[10px] font-[800] uppercase tracking-[.12em]" style={{ color: 'var(--text-tertiary)' }}>{label}</div><div className="mt-0.5 truncate text-[22px] font-[900] tracking-[-.04em]" style={{ color }}>{value}</div><div className="text-[10px]" style={{ color: 'var(--text-tertiary)' }}>{sub}</div></Card>)}</div>

    <div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><Card glow="rgba(139,92,246,.14)"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-[10px] font-[850] uppercase tracking-[.14em]" style={{ color: '#8b5cf6' }}><Network size={13} /> AI Control Plane</div><h2 className="mt-1 text-[18px] font-[900]" style={{ color: 'var(--text-primary)' }}>Smart routing & fallback fabric</h2></div><button onClick={() => router.push('/platform?tab=ai')} className="rounded-full px-3 py-1.5 text-[10px] font-[800]" style={{ background: '#8b5cf612', color: '#8b5cf6' }}>Open AI Control →</button></div><div className="mt-5"><Routing routing={state.routing} /></div><div className="mt-4 grid grid-cols-3 gap-2"><div className="rounded-xl p-2.5" style={{ background: 'var(--bg-subtle)' }}><div className="text-[9px] uppercase" style={{ color: 'var(--text-tertiary)' }}>Models</div><div className="mt-1 text-sm font-[850]" style={{ color: 'var(--text-primary)' }}>{state.models.length}</div></div><div className="rounded-xl p-2.5" style={{ background: 'var(--bg-subtle)' }}><div className="text-[9px] uppercase" style={{ color: 'var(--text-tertiary)' }}>Fallbacks</div><div className="mt-1 text-sm font-[850]" style={{ color: fallback > 10 ? '#f59e0b' : '#10b981' }}>{fallback}%</div></div><div className="rounded-xl p-2.5" style={{ background: 'var(--bg-subtle)' }}><div className="text-[9px] uppercase" style={{ color: 'var(--text-tertiary)' }}>Avg latency</div><div className="mt-1 text-sm font-[850]" style={{ color: 'var(--text-primary)' }}>{state.ai?.avg_latency_ms ?? 0}ms</div></div></div></Card>
      <Card glow="rgba(16,185,129,.12)"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-[10px] font-[850] uppercase tracking-[.14em]" style={{ color: '#10b981' }}><Gauge size={13} /> Health topology</div><h2 className="mt-1 text-[18px] font-[900]" style={{ color: 'var(--text-primary)' }}>Live infrastructure pulse</h2></div><span className="rounded-full px-2.5 py-1 text-[9px] font-[850] uppercase" style={{ color: COLORS[status] ?? '#64748b', background: `${COLORS[status] ?? '#64748b'}12` }}>{status}</span></div><div className="mt-3 flex items-center gap-5"><Donut3D counts={counts} /><div className="min-w-0 flex-1 space-y-2">{Object.entries(counts).map(([name, value]) => <div key={name} className="flex items-center justify-between"><span className="flex items-center gap-2 text-[10.5px] capitalize" style={{ color: 'var(--text-secondary)' }}><span className="h-2 w-2 rounded-full" style={{ background: COLORS[name] ?? '#94a3b8' }} />{name}</span><b className="text-[11px]" style={{ color: 'var(--text-primary)' }}>{value}</b></div>)}</div></div></Card></div>

    <div className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><Card glow="rgba(59,130,246,.12)"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2 text-[10px] font-[850] uppercase tracking-[.14em]" style={{ color: '#3b82f6' }}><LineChart size={13} /> AI telemetry</div><h2 className="mt-1 text-[18px] font-[900]" style={{ color: 'var(--text-primary)' }}>Token flow & request pressure</h2></div><span className="text-[10px]" style={{ color: 'var(--text-tertiary)' }}>30-day window</span></div><div className="mt-4 h-[220px]">{trend.length ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><defs><linearGradient id="ccTokenFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#3b82f6" stopOpacity={.28} /><stop offset="100%" stopColor="#3b82f6" stopOpacity={.02} /></linearGradient></defs><CartesianGrid stroke="rgba(148,163,184,.16)" vertical={false} /><XAxis dataKey="day" tick={{ fontSize: 9, fill: 'var(--text-tertiary)' }} axisLine={false} tickLine={false} /><YAxis tick={{ fontSize: 9, fill: 'var(--text-tertiary)' }} axisLine={false} tickLine={false} tickFormatter={fmt} /><Tooltip contentStyle={{ borderRadius: 12, border: '1px solid var(--border)', background: 'var(--surface)', fontSize: 11 }} /><Area type="monotone" dataKey="tokens" stroke="#3b82f6" fill="url(#ccTokenFill)" strokeWidth={2.5} /></AreaChart></ResponsiveContainer> : <div className="flex h-full items-center justify-center text-xs" style={{ color: 'var(--text-tertiary)' }}>No AI trend data yet.</div>}</div></Card>
      <Card glow="rgba(217,70,239,.12)"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2 text-[10px] font-[850] uppercase tracking-[.14em]" style={{ color: '#d946ef' }}><Layers3 size={13} /> Model intelligence</div><h2 className="mt-1 text-[18px] font-[900]" style={{ color: 'var(--text-primary)' }}>Most active models</h2></div><button onClick={() => router.push('/platform?tab=ai')} className="text-[10px] font-[800]" style={{ color: '#d946ef' }}>Manage →</button></div><div className="mt-4 h-[220px]">{modelBars.length ? <ResponsiveContainer width="100%" height="100%"><BarChart data={modelBars} layout="vertical" margin={{ left: 4, right: 8, top: 4, bottom: 4 }}><CartesianGrid stroke="rgba(148,163,184,.12)" horizontal={false} /><XAxis type="number" hide /><YAxis type="category" dataKey="model" width={92} tick={{ fontSize: 9, fill: 'var(--text-secondary)' }} axisLine={false} tickLine={false} /><Tooltip contentStyle={{ borderRadius: 12, border: '1px solid var(--border)', background: 'var(--surface)', fontSize: 11 }} /><Bar dataKey="requests" fill="#d946ef" radius={[0, 7, 7, 0]} barSize={13} /></BarChart></ResponsiveContainer> : <div className="flex h-full items-center justify-center text-xs" style={{ color: 'var(--text-tertiary)' }}>No model activity yet.</div>}</div></Card></div>

    <div className="grid gap-5 xl:grid-cols-2"><Card glow="rgba(6,182,212,.11)"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2 text-[10px] font-[850] uppercase tracking-[.14em]" style={{ color: '#06b6d4' }}><Building2 size={13} /> Tenant AI footprint</div><h2 className="mt-1 text-[18px] font-[900]" style={{ color: 'var(--text-primary)' }}>Top studios by token usage</h2></div><button onClick={() => router.push('/platform?tab=ai')} className="text-[10px] font-[800]" style={{ color: '#06b6d4' }}>View all →</button></div><div className="mt-4 h-[220px]">{studioBars.length ? <ResponsiveContainer width="100%" height="100%"><BarChart data={studioBars}><CartesianGrid stroke="rgba(148,163,184,.12)" vertical={false} /><XAxis dataKey="studio" tick={{ fontSize: 8.5, fill: 'var(--text-tertiary)' }} axisLine={false} tickLine={false} /><YAxis tick={{ fontSize: 8.5, fill: 'var(--text-tertiary)' }} tickFormatter={fmt} axisLine={false} tickLine={false} /><Tooltip contentStyle={{ borderRadius: 12, border: '1px solid var(--border)', background: 'var(--surface)', fontSize: 11 }} /><Bar dataKey="tokens" fill="#06b6d4" radius={[7, 7, 0, 0]} barSize={28} /></BarChart></ResponsiveContainer> : <div className="flex h-full items-center justify-center text-xs" style={{ color: 'var(--text-tertiary)' }}>No studio AI usage yet.</div>}</div></Card>
      <Card glow="rgba(245,158,11,.11)"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2 text-[10px] font-[850] uppercase tracking-[.14em]" style={{ color: '#f59e0b' }}><Workflow size={13} /> Operator fabric</div><h2 className="mt-1 text-[18px] font-[900]" style={{ color: 'var(--text-primary)' }}>FreeLLMAPI-inspired modules</h2></div><span className="rounded-full px-2 py-1 text-[9px] font-[800]" style={{ background: '#f59e0b14', color: '#b45309' }}>REAL DATA</span></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3">{[
        { label: 'Models', Icon: Layers3, tab: 'ai' }, { label: 'Routing', Icon: Route, tab: 'ai' }, { label: 'Analytics', Icon: LineChart, tab: 'analytics' }, { label: 'Fallbacks', Icon: Workflow, tab: 'ai' }, { label: 'Keys & access', Icon: KeyRound, tab: 'security' }, { label: 'Agents', Icon: WandSparkles, tab: 'ai' }, { label: 'Playground', Icon: PlayCircle, tab: 'ai' }, { label: 'Fusion', Icon: BrainCircuit, tab: 'ai' }, { label: 'Logs', Icon: Activity, tab: 'health' },
      ].map(({ label, Icon, tab }) => <button key={label} onClick={() => router.push(`/platform?tab=${tab}`)} className="group rounded-[16px] border p-3 text-left transition-transform hover:-translate-y-0.5" style={{ borderColor: 'var(--border)', background: 'var(--bg-subtle)' }}><span className="flex h-8 w-8 items-center justify-center rounded-xl" style={{ background: '#f59e0b12', color: '#f59e0b' }}><Icon size={15} /></span><span className="mt-2 block text-[11px] font-[800]" style={{ color: 'var(--text-primary)' }}>{label}</span><span className="mt-0.5 flex items-center gap-1 text-[9px]" style={{ color: 'var(--text-tertiary)' }}>Open module <ChevronRight size={10} /></span></button>)}
      </div></Card></div>

    <div><div className="mb-3 flex items-end justify-between"><div><div className="text-[10px] font-[850] uppercase tracking-[.16em]" style={{ color: 'var(--text-tertiary)' }}>Command modules</div><h2 className="mt-0.5 text-[18px] font-[900]" style={{ color: 'var(--text-primary)' }}>Everything the operator needs</h2></div><div className="text-[10px]" style={{ color: 'var(--text-tertiary)' }}>Multi-tenant control plane</div></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6">{MODULES.map(([label, Icon, tab, color, hint]) => <button key={label} onClick={() => router.push(`/platform?tab=${tab}`)} className="group rounded-[20px] border p-3.5 text-left transition-all hover:-translate-y-1 hover:shadow-xl" style={{ borderColor: 'var(--border)', background: 'linear-gradient(145deg,color-mix(in srgb,var(--surface) 96%,transparent),var(--bg-subtle))' }}><div className="flex items-center justify-between"><span className="flex h-9 w-9 items-center justify-center rounded-[13px]" style={{ color, background: `${color}12` }}><Icon size={16} /></span><ChevronRight size={13} style={{ color: 'var(--text-disabled)' }} /></div><div className="mt-3 text-[11px] font-[850]" style={{ color: 'var(--text-primary)' }}>{label}</div><div className="mt-0.5 text-[9.5px]" style={{ color: 'var(--text-tertiary)' }}>{hint}</div></button>)}</div></div>
    <div className="flex flex-wrap items-center justify-center gap-2 px-3 pt-1 text-center text-[10px]" style={{ color: 'var(--text-tertiary)' }}><span>Live platform snapshot</span><span>·</span><span>real-time control plane</span><span>·</span><span>{state.snapshot?.duration_ms ?? 0}ms collection</span><span>·</span><span>{state.models.length} AI model records</span></div>
  </div>;
}
