'use client';

// The weekly report: a PDF for the trainer, and a message for the client.
//
// ── Why these are two separate actions ────────────────────────────────────
//
// The obvious design is one "Send report on WhatsApp" button that texts the
// client a link to the PDF. It does not work, for two independent reasons, and
// both are worth stating because they are invisible until a client complains.
//
// First, WhatsApp's share URL carries TEXT only. There is no parameter that
// attaches a file. Sending a document means the trainer picks it in WhatsApp
// themselves — no web page can do it for them.
//
// Second, and more decisive: the PDF lives behind the app's session. Clients
// have no login in this system — it is staff-operated by design — so a link to
// the report would give them a sign-in page. Putting that link in a message
// would send every client a URL that cannot be opened.
//
// So: the button generates the PDF and opens it for the TRAINER, who can save
// or attach it. The share action composes the week as a message a client can
// actually read, with no link in it.
//
// ── Why the message has no numbers the client cannot check ────────────────
//
// It carries attendance, volume and records — all measured. No score, no
// grade, no "you are ahead of schedule". A message from a coach is read as a
// judgement about the person, and a judgement generated by arithmetic nobody
// chose is worse than no message.

import { useState } from 'react';
import { FileText, Loader2, MessageCircle } from 'lucide-react';
import { api } from '@/lib/api';
import type { TrainingAnalytics } from '@/lib/api';
import { useToast } from '@/lib/toast';

export interface WeeklyReportProps {
  clientId: string;
  clientName?: string | null;
  /** Used to compose the share message. */
  stats: TrainingAnalytics | null;
}

export default function WeeklyReport({ clientId, clientName, stats }: WeeklyReportProps) {
  const { toast } = useToast();
  const [note, setNote] = useState('');
  const [busy, setBusy] = useState(false);

  const build = async () => {
    setBusy(true);
    try {
      const { data } = await api.progress.workoutLog.weeklyReport({
        client_id: clientId,
        coach_note: note.trim() || undefined,
      });
      // A new tab, not a download attribute: the file is served from the API
      // origin behind the session cookie, and a cross-origin download link
      // would arrive unauthenticated.
      window.open(data.url, '_blank', 'noopener,noreferrer');
    } catch {
      toast.error('Could not build the report');
    } finally {
      setBusy(false);
    }
  };

  const share = () => {
    const text = composeMessage({ clientName, stats, note: note.trim() });
    // No number in the URL: wa.me without one opens WhatsApp's own contact
    // picker. Prefilling from a stored mobile would put a named client's
    // training summary one wrong digit away from a stranger, and the trainer
    // knows who they are messaging better than the database does.
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank', 'noopener,noreferrer');
  };

  return (
    <div className="rounded-[20px] p-4" style={{ background: 'var(--bg-card)', border: '1px solid var(--border)' }}>
      <div className="mb-1 flex items-center gap-2">
        <div className="flex h-7 w-7 items-center justify-center rounded-[8px]"
          style={{ background: 'rgba(37,99,235,0.14)', color: '#2563eb' }}>
          <FileText size={14} />
        </div>
        <span className="text-[12.5px] font-[700]" style={{ color: 'var(--text-primary)' }}>
          This week&rsquo;s report
        </span>
      </div>
      <p className="mb-3 text-[11.5px]" style={{ color: 'var(--text-muted)' }}>
        Built from this week&rsquo;s logged sessions.
      </p>

      <label className="mb-3 block">
        <span className="mb-1.5 block text-[11px] font-[700] uppercase tracking-wide" style={{ color: 'var(--text-muted)' }}>
          A note for your client (optional)
        </span>
        <textarea
          value={note}
          onChange={(e) => setNote(e.target.value)}
          rows={2}
          placeholder="What you want them to take from this week…"
          className="min-h-[66px] w-full resize-y rounded-[12px] px-3 py-2.5 text-[13px] outline-none"
          style={{ background: 'var(--bg-subtle)', border: '1px solid var(--border)', color: 'var(--text-primary)' }}
        />
      </label>

      <div className="flex flex-wrap gap-2">
        <button
          type="button"
          onClick={build}
          disabled={busy}
          className="flex h-[44px] flex-1 items-center justify-center gap-2 rounded-[14px] px-4 text-[13px] font-[700] text-white disabled:opacity-60"
          style={{ background: 'var(--brand)' }}
        >
          {busy ? <Loader2 size={15} className="animate-spin" /> : <FileText size={15} />}
          {busy ? 'Building…' : 'Open PDF'}
        </button>
        <button
          type="button"
          onClick={share}
          className="flex h-[44px] flex-1 items-center justify-center gap-2 rounded-[14px] px-4 text-[13px] font-[700]"
          style={{ background: 'var(--bg-subtle)', border: '1px solid var(--border)', color: '#059669' }}
        >
          <MessageCircle size={15} /> Share summary
        </button>
      </div>

      <p className="mt-2 text-[10.5px]" style={{ color: 'var(--text-muted)' }}>
        Share sends the week as a message. To send the PDF itself, open it and attach it in WhatsApp —
        the file is behind your studio login, so a link would not open for your client.
      </p>
    </div>
  );
}

/**
 * The week, as something a person would send.
 *
 * Only measured things: sessions attended, volume moved, records broken. No
 * score and no encouragement generated by arithmetic — the trainer's own note
 * is the only opinion in it, and it is theirs.
 */
export function composeMessage({
  clientName, stats, note,
}: { clientName?: string | null; stats: TrainingAnalytics | null; note?: string }) {
  const lines: string[] = [];
  lines.push(`${clientName ? `${clientName}, here` : 'Here'} is your training week 💪`);

  if (stats?.adherence?.pct != null) {
    const { completed, planned } = stats.adherence;
    lines.push(`Sessions: ${completed} of ${planned}`);
  }

  const prs = stats?.prs ?? [];
  if (prs.length > 0) {
    lines.push('');
    lines.push(`Personal best${prs.length === 1 ? '' : 's'}:`);
    // Three at most: a message listing eleven records is not read, it is
    // scrolled past.
    for (const p of prs.slice(0, 3)) {
      const load = [p.weight_kg != null ? `${p.weight_kg} kg` : null, p.reps != null ? `${p.reps} reps` : null]
        .filter(Boolean).join(' × ');
      lines.push(`• ${p.exercise_name} — ${load}`);
    }
  }

  if (note) {
    lines.push('');
    lines.push(note);
  }
  return lines.join('\n');
}
