'use client';

import { useState } from 'react';
import { BarChart3, Loader2, Sparkles, TrendingUp, TrendingDown, Minus, AlertCircle, AlertTriangle } from 'lucide-react';
import { api } from '@/lib/api';
import type { AiBusinessInsights } from '@/lib/api';
import Guard from '@/components/Guard';
import AppShell from '@/components/AppShell';

const PERIODS = [
  { label: 'Last 7 days', value: '7d' },
  { label: 'Last 30 days', value: '30d' },
  { label: 'Last 90 days', value: '90d' },
  { label: 'Last 6 months', value: '180d' },
  { label: 'Last year', value: '365d' },
];

function TrendIcon({ direction }: { direction: string }) {
  if (direction === 'up' || direction === 'increasing') return <TrendingUp className="w-4 h-4 text-green-500" />;
  if (direction === 'down' || direction === 'decreasing') return <TrendingDown className="w-4 h-4 text-red-500" />;
  return <Minus className="w-4 h-4 text-gray-400" />;
}

function fmt(n: number): string {
  if (n >= 100000) return `₹${(n / 100000).toFixed(1)}L`;
  if (n >= 1000) return `₹${(n / 1000).toFixed(1)}K`;
  return `₹${n}`;
}

export default function BusinessInsightsPage() {
  const [period, setPeriod] = useState('30d');
  const [loading, setLoading] = useState(false);
  const [insights, setInsights] = useState<AiBusinessInsights | null>(null);
  const [meta, setMeta] = useState<{ model?: string; tier?: string; used_fallback?: boolean } | null>(null);
  const [error, setError] = useState('');

  const handleGenerate = async () => {
    setError('');
    setLoading(true);
    setInsights(null);
    setMeta(null);
    try {
      const days = parseInt(period);
      const to = new Date();
      const from = new Date(to.getTime() - days * 86400 * 1000);
      const fmt = (d: Date) => d.toISOString().slice(0, 10);
      const res = await api.ai.businessInsights({ from: fmt(from), to: fmt(to) });
      setInsights(res.data);
      setMeta({ model: res.model, tier: res.tier, used_fallback: res.used_fallback });
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : 'Failed to generate insights.';
      if (msg.includes('403') || msg.toLowerCase().includes('forbidden') || msg.toLowerCase().includes('admin')) {
        setError('Business Insights is restricted to admin accounts.');
      } else {
        setError(msg);
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <Guard role="admin">
      <AppShell title="AI Business Insights">
        <div className="max-w-4xl mx-auto space-y-8">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-violet-500/10">
              <BarChart3 className="w-6 h-6 text-violet-600" />
            </div>
            <div>
              <h1 className="text-2xl font-bold text-gray-900">AI Business Insights</h1>
              <p className="text-gray-500 text-sm">AI-powered analysis of your studio&apos;s performance and growth opportunities</p>
            </div>
          </div>

          <div className="p-6 rounded-2xl border border-gray-200 bg-white space-y-4">
            <div className="space-y-1">
              <label className="text-sm font-medium text-gray-800">Analysis Period</label>
              <div className="flex flex-wrap gap-2">
                {PERIODS.map((p) => (
                  <button
                    key={p.value}
                    onClick={() => setPeriod(p.value)}
                    className={`px-3 py-1.5 rounded-lg text-sm font-medium transition-colors ${period === p.value ? 'bg-violet-600 text-white' : 'border border-gray-200 text-gray-600 hover:bg-gray-50'}`}
                  >
                    {p.label}
                  </button>
                ))}
              </div>
            </div>

            {error && (
              <div className="flex items-start gap-2 text-sm text-red-600 bg-red-50 rounded-lg px-3 py-2">
                <AlertCircle className="w-4 h-4 shrink-0 mt-0.5" />
                {error}
              </div>
            )}

            <button
              onClick={handleGenerate}
              disabled={loading}
              className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-violet-600 text-white font-medium text-sm hover:bg-violet-700 disabled:opacity-50 transition-colors"
            >
              {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
              {loading ? 'Analysing…' : 'Generate Insights'}
            </button>
          </div>

          {insights && (
            <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-300">
              {meta && (
                <div className="flex items-center gap-2 text-xs text-gray-500">
                  <Sparkles className="w-3 h-3" />
                  <span>Generated by <code className="bg-gray-100 px-1 rounded text-gray-700">{meta.model}</code></span>
                  {meta.used_fallback && <span className="text-yellow-600">(fallback model)</span>}
                </div>
              )}

              <div className="p-5 rounded-2xl border border-gray-200 bg-white">
                <h2 className="text-lg font-bold text-gray-900">Executive Summary</h2>
                <p className="text-sm text-gray-500 mt-2">{insights.executive_summary || insights.summary}</p>
                {insights.period && (
                  <div className="mt-2 text-xs text-gray-400">Period: <strong className="text-gray-700">{insights.period}</strong></div>
                )}
              </div>

              {insights.kpis && (
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                  {[
                    { label: 'MRR', value: fmt(insights.kpis.mrr) },
                    { label: 'Retention', value: `${insights.kpis.retention_rate_pct}%` },
                    { label: 'Session Utilisation', value: `${insights.kpis.avg_session_utilisation_pct}%` },
                    { label: 'Revenue / Trainer', value: fmt(insights.kpis.revenue_per_trainer) },
                  ].map((k) => (
                    <div key={k.label} className="p-4 rounded-xl border border-gray-200 bg-white text-center">
                      <div className="text-xl font-bold text-gray-900">{k.value}</div>
                      <div className="text-xs text-gray-500 mt-1">{k.label}</div>
                    </div>
                  ))}
                </div>
              )}

              {insights.trends?.length ? (
                <div className="p-5 rounded-2xl border border-gray-200 bg-white space-y-3">
                  <h3 className="font-semibold text-gray-900">Trends</h3>
                  {insights.trends.map((t, i) => (
                    <div key={i} className="flex items-center gap-3 py-2 border-b border-gray-100 last:border-0">
                      <TrendIcon direction={t.direction} />
                      <div className="flex-1">
                        <div className="text-sm font-medium text-gray-800">{t.metric}</div>
                        <div className="text-xs text-gray-500">{t.insight}</div>
                      </div>
                      <span className={`text-sm font-semibold ${t.direction === 'up' || t.direction === 'increasing' ? 'text-green-600' : t.direction === 'down' || t.direction === 'decreasing' ? 'text-red-600' : 'text-gray-400'}`}>
                        {t.change_pct > 0 ? '+' : ''}{t.change_pct}%
                      </span>
                    </div>
                  ))}
                </div>
              ) : null}

              {insights.opportunities?.length ? (
                <div className="p-5 rounded-2xl border border-green-200 bg-green-50 space-y-3">
                  <h3 className="font-semibold text-green-700">Growth Opportunities</h3>
                  {insights.opportunities.map((o, i) => (
                    <div key={i} className="flex gap-3">
                      <div className="w-6 h-6 rounded-full bg-green-100 text-green-700 text-xs font-bold flex items-center justify-center shrink-0">{i + 1}</div>
                      <div>
                        <div className="text-sm font-medium text-green-800">{o.opportunity}</div>
                        <div className="flex gap-4 mt-0.5 text-xs text-gray-500">
                          <span>Impact: {o.estimated_impact}</span>
                          <span>Effort: {o.effort}</span>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              ) : null}

              {insights.risks?.length ? (
                <div className="p-5 rounded-2xl border border-yellow-200 bg-yellow-50 space-y-3">
                  <div className="flex items-center gap-2 font-semibold text-yellow-700">
                    <AlertTriangle className="w-4 h-4" />
                    Business Risks
                  </div>
                  {insights.risks.map((r, i) => (
                    <div key={i} className="border-b border-yellow-200 pb-3 last:border-0 last:pb-0">
                      <div className="flex items-center gap-2">
                        <span className="text-sm font-medium text-yellow-800">{r.risk}</span>
                        <span className={`text-[10px] px-1.5 py-0.5 rounded font-medium ${r.severity === 'high' ? 'bg-red-100 text-red-700' : r.severity === 'medium' ? 'bg-yellow-100 text-yellow-700' : 'bg-gray-100 text-gray-500'}`}>
                          {r.severity}
                        </span>
                      </div>
                      <p className="text-xs text-yellow-700 mt-1">{r.recommended_action}</p>
                    </div>
                  ))}
                </div>
              ) : null}

              {insights.recommendations?.length ? (
                <div className="p-5 rounded-2xl border border-gray-200 bg-white space-y-3">
                  <h3 className="font-semibold text-gray-900">Action Plan</h3>
                  {insights.recommendations
                    .slice()
                    .sort((a, b) => a.priority - b.priority)
                    .map((r, i) => (
                    <div key={i} className="flex items-start gap-3 py-2 border-b border-gray-100 last:border-0">
                      <div className="w-6 h-6 rounded-full bg-violet-500/10 text-violet-600 text-xs font-bold flex items-center justify-center shrink-0 mt-0.5">{r.priority}</div>
                      <div className="flex-1">
                        <div className="text-sm font-medium text-gray-800">{r.action}</div>
                        {r.rationale && <div className="text-xs text-gray-500 mt-0.5">{r.rationale}</div>}
                      </div>
                      {r.timeframe && <div className="text-xs text-gray-400 shrink-0">{r.timeframe}</div>}
                    </div>
                  ))}
                </div>
              ) : null}
            </div>
          )}
        </div>
      </AppShell>
    </Guard>
  );
}
